namespace Shop.Contract.Services.V1.Suppliers;

public class Response
{
    public record SupplierResponse(
     Guid Id,
     string Code,
     string Name,
     string? ShortName,
     string? TaxCode,
     string? Phone,
     string? Email,
     string? Website,
     string? ContactName,
     string? ContactPhone,
     string? ContactEmail,
     Guid ProvinceId,
     Guid WardId,
     string? AddressLine,
     string? FullAddress,
     string? BankName,
     string? BankAccountNo,
     string? BankAccountName,
     int PaymentTermDays,
     byte? Rating,
     string? Note,
     bool IsActive);
    public record SupplierDetailResponse(Guid Id,
     string Code,
     string Name,
     string? ShortName,
     string? TaxCode,
     string? Phone,
     string? Email,
     string? Website,
     string? ContactName,
     string? ContactPhone,
     string? ContactEmail,
     Guid ProvinceId,
     Guid WardId,
     string? AddressLine,
     string? FullAddress,
     string? BankName,
     string? BankAccountNo,
     string? BankAccountName,
     int PaymentTermDays,
     byte? Rating,
     string? Note,
     bool IsActive);
}
